# Generated by Django 5.0.2 on 2024-02-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educy', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
