# Generated by Django 5.0.2 on 2024-02-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educy', '0003_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date_joined', models.CharField(max_length=255)),
            ],
        ),
    ]
