# Generated by Django 5.0.2 on 2024-02-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educy', '0004_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='product_name',
            new_name='username',
        ),
    ]
