# Generated by Django 5.0.2 on 2024-03-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educy', '0006_bag_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='product_image',
            field=models.CharField(default='No image', max_length=255),
        ),
        migrations.AddField(
            model_name='bag',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
